name: http
version: 0.12.0+1
homepage: https://github.com/priezz/universal_http
description: A composable, multi-platform, Future-based API for HTTP requests.

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  http_parser: ^4.0.0
  node_http: ^1.0.1
  path: ^1.8.0

dev_dependencies:
  analyzer: ^0.41.2
  pedantic: ^1.10.0
  test: ^1.16.0
